[package]
name = "hello"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.12.2"
tokio = { version = "1.40.0", features = ["macros", "rt-multi-thread"] }
prost = "0.13.2"

[build-dependencies]
tonic-build = "0.12.2"
